name: tests-unitaires

on:
  push:
    branches: [main]

jobs:
  tests_unitaires:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: [1.17, 1.18, 1.19]

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2

      - name: Configuration de Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Exécuter les tests unitaires
        run: go test ./...
